# -*- coding: utf-8 -*-
"""PINN para Opciones Americanas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYDxyljzDZ9ultqa2dfHuwjwM2Sl-nzM

<center>

Entrega final del reto

**PINN para Opciones Americanas**

Análisis numérico para la optimización no-lineal (Gpo 601)


<br>

Zareth Abigail Rodríguez Reyes - A01659378

José Juan González Rebolledo - A01753090

<br>

Profesor: José Luis Gómez

03/06/2026

---

## Sección 1. Instalación e imports

En esta sección cargamos las librerías necesarias para descargar datos de SPY, construir el método binomial y entrenar la PINN con PyTorch.
"""

!pip install yfinance -q

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

import torch
import torch.nn as nn
import torch.autograd as autograd

np.random.seed(1234)
torch.manual_seed(1234)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

"""## Sección 2. Datos de SPY y parámetros financieros

Se utilizaron precios históricos de SPY correspondientes a los últimos 60 días hábiles del segundo semestre de 2024 (Entre Julio y Diciembre). A partir de estos datos se obtuvo el precio inicial del activo $S_0$ y se estimó la volatilidad anualizada mediante los rendimientos logarítmicos diarios.

El precio de ejercicio se fijó como $K \approx S_0$, por lo que se analiza una **Opción Put** americana at-the-money.

El vencimiento se definió como $T=60/252$, considerando aproximadamente 252 días hábiles por año. La tasa libre de riesgo utilizada fue $r=4.5\%$ anual, como una aproximación razonable para instrumentos de corto plazo en dólares.

<br>

Al igual que el artículo, se emplean los parámetros financieros fundamentales requeridos por el modelo de Black-Scholes. Para este trabajo dichos parámetros se estiman a partir de los datos históricos del SPY, mientras que el artículo utiliza un conjunto de parámetros previamente definidos para sus experimentos.

"""

ticker = "SPY"

start_date = "2024-07-01"
end_date = "2024-12-31"

data = yf.download(ticker, start=start_date, end=end_date, auto_adjust=True)
data = data[["Close"]].dropna()

# Tomamos 60 días hábiles dentro del segundo semestre de 2024
data = data.tail(60)

S0 = float(data["Close"].iloc[-1])
returns = np.log(data["Close"] / data["Close"].shift(1)).dropna()
sigma = float(returns.std() * np.sqrt(252))

K = round(S0 * 1.00, 2)
T = 60 / 252
r = 0.045
Smax = 2 * K

print("S0 =", S0)
print("K =", K)
print("sigma =", sigma)
print("r =", r)
print("T =", T)
print("Número de datos:", len(data))

"""## Sección 3. Método binomial americano

El árbol binomial se utiliza como método clásico de referencia para valuar la opción put americana. En cada nodo del árbol se calcula el valor de continuación y se compara contra el valor de ejercer inmediatamente.

Esta comparación permite incorporar la característica principal de las opciones americanas: la posibilidad de ejercicio anticipado. Además, el método binomial permite estimar una frontera óptima de ejercicio, que posteriormente se utiliza para comparar la frontera aprendida por la PINN.

<br>

De manera similar al artículo, se utiliza el método binomial como referencia numérica para validar los resultados de la PINN. Adicionalmente, se extrae la frontera óptima de ejercicio y se incorpora como información auxiliar durante el entrenamiento.
"""

def american_put_binomial(S0, K, r, sigma, T, N):
    dt = T / N
    u = np.exp(sigma * np.sqrt(dt))
    d = 1 / u
    disc = np.exp(-r * dt)
    q = (np.exp(r * dt) - d) / (u - d)

    # precios al vencimiento
    S = np.array([S0 * u**j * d**(N-j) for j in range(N+1)])
    V = np.maximum(K - S, 0)

    boundary = []

    for step in range(N-1, -1, -1):
        # reconstruir correctamente los precios en este tiempo
        S = np.array([S0 * u**j * d**(step-j) for j in range(step+1)])

        continuation = disc * ((1-q) * V[:step+1] + q * V[1:step+2])
        exercise = np.maximum(K - S, 0)

        V = np.maximum(continuation, exercise)

        exercise_nodes = S[(exercise > 0) & (exercise >= continuation)]

        if len(exercise_nodes) > 0:
            boundary.append([step * dt, np.max(exercise_nodes)])
        else:
            boundary.append([step * dt, np.nan])

    boundary = np.array(boundary[::-1])
    return V[0], boundary

N_binomial = 300
binomial_price, binomial_boundary = american_put_binomial(S0, K, r, sigma, T, N_binomial)

print("Precio binomial put americana:", binomial_price)

# Frontera binomial limpia para usar durante el entrenamiento

boundary_times = binomial_boundary[:, 0]
boundary_values = binomial_boundary[:, 1]

mask_boundary = ~np.isnan(boundary_values)

boundary_times_clean = boundary_times[mask_boundary]
boundary_values_clean = boundary_values[mask_boundary]

"""## Sección 4. Datos de referencia para comparar

Se construyó una malla de precios del activo subyacente y para cada valor se calculó el precio de la opción mediante el método binomial. Estos valores funcionan como una referencia numérica para evaluar la calidad de la aproximación obtenida por la PINN.

La gráfica de referencia muestra el comportamiento esperado de una opción put: cuando el precio del activo es bajo, el valor de la opción es alto; conforme el precio del activo aumenta, el valor de la put disminuye hasta acercarse a cero.

<br>

Siguiendo la filosofía del artículo, se construye una referencia numérica para evaluar la precisión de la PINN. A diferencia del trabajo original, los valores obtenidos mediante el método binomial también son utilizados como información supervisada dentro del proceso de entrenamiento.
"""

def american_put_binomial_grid(S_values, K, r, sigma, T, N=200):
    prices = []
    for S in S_values:
        price, _ = american_put_binomial(float(S), K, r, sigma, T, N)
        prices.append(price)
    return np.array(prices)

S_grid = np.linspace(0.05*K, Smax, 150)
V_binomial_grid = american_put_binomial_grid(S_grid, K, r, sigma, T, N=150)

plt.figure(figsize=(7,4))
plt.plot(S_grid, V_binomial_grid, label="Binomial americano")
plt.xlabel("Precio del activo S")
plt.ylabel("Precio de la opción")
plt.title("Referencia binomial para put americana")
plt.grid(True)
plt.legend()
plt.show()

"""## Sección 5. Arquitectura de la PINN y Frontera Móvil

El modelo utiliza dos redes neuronales.

* La primera aproxima el precio de la opción $V(S,t)$, recibiendo como entradas el precio del activo $S$ y el tiempo $t$.
* La segunda red aproxima la frontera óptima de ejercicio $B(t)$.

<br>

Al igual que en el artículo, se emplean dos redes neuronales: una para aproximar el precio de la opción y otra para aproximar la frontera libre. No obstante, se adopta una arquitectura PINN directa, prescindiendo de la solución aproximada parametrizada y de la capa de expansión de datos propuestas en el trabajo original.

### Red para el precio de la opción $V(S,t)$
"""

# Red para el precio de la opción V(S,t)
class PINN(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(2, 64),
            nn.Tanh(),
            nn.Linear(64, 64),
            nn.Tanh(),
            nn.Linear(64, 64),
            nn.Tanh(),
            nn.Linear(64, 1),
            nn.Softplus()
        )

    def forward(self, S, t):
        S_norm = S / Smax
        t_norm = t / T
        x = torch.cat([S_norm, t_norm], dim=1)
        V_norm = self.net(x)
        return K * V_norm

"""### Red para la frontera móvil S*(t)

Se incorporó conocimiento financiero básico al modelo para que la frontera aprendida permaneciera por debajo del strike $K$, ya que una frontera por encima de ese valor no tendría interpretación financiera para una opción put americana. Esta restricción mejora la estabilidad del entrenamiento sin imponer la solución exacta.
"""

# Red para la frontera móvil S*(t)
class BoundaryNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(1, 32),
            nn.Tanh(),
            nn.Linear(32, 32),
            nn.Tanh(),
            nn.Linear(32, 1),
            nn.Sigmoid()
        )

    def forward(self, t):
        t_norm = t / T

        # La frontera de una put americana debe estar por debajo de K.
        # La acotamos a una región financieramente razonable: [K - 0.15K, K]
        lower = 0.85 * K
        upper = K

        return lower + (upper - lower) * self.net(t_norm)

model = PINN().to(device)
boundary_model = BoundaryNet().to(device)

optimizer = torch.optim.Adam(
    list(model.parameters()) + list(boundary_model.parameters()),
    lr=1e-3
)

"""## Sección 6. Puntos de colocación

En esta sección se definen los puntos de colocación utilizados durante el entrenamiento. Los puntos interiores se emplean para evaluar el residuo de la ecuación de Black-Scholes, mientras que otros conjuntos de puntos se usan para imponer la condición terminal, las condiciones de frontera y la comparación con el método binomial.

Separar estos puntos permite identificar con claridad dónde se evalúa cada término de la función de pérdida.

<br>

De forma similar al artículo, el entrenamiento se realiza mediante puntos interiores y puntos asociados a las condiciones de frontera y terminales. Para simplificar la implementación, se utiliza únicamente muestreo uniforme dentro del dominio de entrenamiento.
"""

def generar_puntos_colocacion(n_pde=2000, n_bc=500, n_data=300):
    # Puntos interiores para el residuo de Black-Scholes
    S_pde = torch.rand(n_pde, 1).to(device) * Smax
    t_pde = torch.rand(n_pde, 1).to(device) * T

    # Puntos para condición terminal t = T
    S_T = torch.linspace(0, Smax, n_bc).reshape(-1,1).to(device)
    t_T = T * torch.ones_like(S_T).to(device)

    # Puntos para fronteras S = 0 y S = Smax
    t_b = torch.linspace(0, T, n_bc).reshape(-1,1).to(device)
    S_0 = torch.zeros_like(t_b).to(device)
    S_m = Smax * torch.ones_like(t_b).to(device)

    # Puntos de datos binomiales
    idx = np.random.choice(len(S_grid), n_data, replace=True)
    S_data_np = S_grid[idx].reshape(-1,1)
    V_data_np = V_binomial_grid[idx].reshape(-1,1)

    S_data = torch.tensor(S_data_np, dtype=torch.float32).to(device)
    t_data = torch.zeros_like(S_data).to(device)
    V_data = torch.tensor(V_data_np, dtype=torch.float32).to(device)

    return S_pde, t_pde, S_T, t_T, t_b, S_0, S_m, S_data, t_data, V_data

"""## Sección 7. Función de pérdida

La función de pérdida combina restricciones matemáticas, financieras y datos de referencia.

Incluye:
* El residuo de la ecuación de Black-Scholes
* La condición terminal al vencimiento
* Las condiciones de frontera
* La restricción americana $V(S,t)\geq \max(K-S,0)$
* Comparación contra precios generados por el método binomial.

También se incorporan condiciones sobre la frontera móvil:

* La condición de valor $V(B(t),t)=K-B(t)$
* La condición de smooth pasting $V_S(B(t),t)=-1$
* Pérdida adicional que guía la frontera de la PINN con la frontera obtenida por el método binomial.

<br>

La función de pérdida conserva los términos físicos principales utilizados en el artículo, incluyendo el residuo de la ecuación diferencial y las condiciones asociadas a la frontera libre. Adicionalmente, se incorporan términos supervisados basados en precios y fronteras obtenidos mediante el método binomial, así como restricciones financieras propias de las opciones americanas.
"""

def pinn_loss(model, n_pde=2000, n_bc=500, n_data=300):
    # Se llaman los puntos de colocación definidos en la sección anterior
    S, t, S_T, t_T, t_0, S_0, S_m, S_data, t_data, V_data = generar_puntos_colocacion(
        n_pde=n_pde,
        n_bc=n_bc,
        n_data=n_data
    )

    # Activamos gradientes en puntos interiores para calcular derivadas
    S.requires_grad = True
    t.requires_grad = True

    # Residuo de Black-Scholes
    V = model(S, t)

    V_S = autograd.grad(
        V, S,
        grad_outputs=torch.ones_like(V),
        create_graph=True
    )[0]

    V_t = autograd.grad(
        V, t,
        grad_outputs=torch.ones_like(V),
        create_graph=True
    )[0]

    V_SS = autograd.grad(
        V_S, S,
        grad_outputs=torch.ones_like(V_S),
        create_graph=True
    )[0]

    residual = V_t + 0.5*sigma**2*S**2*V_SS + r*S*V_S - r*V
    loss_pde = torch.mean(residual**2)

    # Condición terminal: V(S,T) = max(K-S,0)
    V_T = model(S_T, t_T)
    payoff_T = torch.maximum(K - S_T, torch.zeros_like(S_T))
    loss_terminal = torch.mean((V_T - payoff_T)**2)

    # Frontera S = 0
    V_0 = model(S_0, t_0)
    target_0 = K * torch.exp(-r * (T - t_0))
    loss_s0 = torch.mean((V_0 - target_0)**2)

    # Frontera S = Smax
    V_m = model(S_m, t_0)
    loss_smax = torch.mean(V_m**2)

    # Condición americana: V >= payoff
    payoff_interior = torch.maximum(K - S, torch.zeros_like(S))
    loss_american = torch.mean(torch.relu(payoff_interior - V)**2)

    # Datos binomiales en t = 0
    V_pred_data = model(S_data, t_data)
    loss_data = torch.mean((V_pred_data - V_data)**2)

    # Frontera móvil aproximada por la red BoundaryNet
    S_b = boundary_model(t_0)

    V_b = model(S_b, t_0)
    payoff_b = K - S_b

    # Condición de valor sobre la frontera: V(B(t),t) = K - B(t)
    loss_boundary_value = torch.mean((V_b - payoff_b)**2)

    # Smooth pasting: V_S(B(t),t) = -1
    V_S_b = autograd.grad(
        V_b, S_b,
        grad_outputs=torch.ones_like(V_b),
        create_graph=True
    )[0]

    # Datos de frontera binomial para guiar B_PINN(t)

    idx_b = np.random.choice(
        len(boundary_times_clean),
        min(n_bc, len(boundary_times_clean)),
        replace=True
    )

    t_boundary_np = boundary_times_clean[idx_b].reshape(-1,1)
    B_boundary_np = boundary_values_clean[idx_b].reshape(-1,1)

    t_boundary = torch.tensor(
        t_boundary_np,
        dtype=torch.float32
    ).to(device)

    B_boundary = torch.tensor(
        B_boundary_np,
        dtype=torch.float32
    ).to(device)

    B_pred = boundary_model(t_boundary)

    loss_boundary_data = torch.mean(
        (B_pred - B_boundary)**2
    )

    loss_boundary_derivative = torch.mean((V_S_b + 1)**2)

    total_loss = (
        loss_pde
        + 10*loss_terminal
        + loss_s0
        + loss_smax
        + 5*loss_american
        + 5*loss_data
        + 10*loss_boundary_value
        + 5*loss_boundary_derivative
        + 10*loss_boundary_data
    )

    return total_loss, loss_pde, loss_terminal, loss_data

"""## Sección 8. Entrenamiento

Durante el entrenamiento se minimiza la pérdida total mediante el optimizador Adam.

<br>

El procedimiento de entrenamiento sigue el esquema general descrito en el artículo mediante optimización conjunta de ambas redes utilizando Adam. La principal diferencia es la incorporación de información supervisada proveniente del método binomial y la utilización de una configuración de entrenamiento más compacta.
"""

epochs = 5000
loss_history = []

for epoch in range(epochs):
    optimizer.zero_grad()

    loss, loss_pde, loss_terminal, loss_data = pinn_loss(model)
    loss.backward()
    optimizer.step()

    loss_history.append(loss.item())

    if epoch % 500 == 0:
        print(
            f"Epoch {epoch} | Loss: {loss.item():.6f} | "
            f"PDE: {loss_pde.item():.6f} | "
            f"Terminal: {loss_terminal.item():.6f} | "
            f"Data: {loss_data.item():.6f}"
        )

plt.figure(figsize=(7,4))
plt.plot(loss_history)
plt.yscale("log")
plt.xlabel("Época")
plt.ylabel("Loss")
plt.title("Evolución de la pérdida")
plt.grid(True)
plt.show()

"""La gráfica de pérdida al inicio muestra una disminución clara durante las primeras épocas. Y se estabiliza suavemente después, lo cual indica que la red aprende progresivamente las restricciones del problema.

Las oscilaciones al final del entrenamiento son esperadas debido al muestreo aleatorio de puntos de colocación.

## Sección 9. Evaluación del precio de la opción

Después del entrenamiento, se evalúa la PINN sobre una malla de precios del activo y se compara contra el método binomial.

<br>

Al igual que en el artículo, se hace la comparación con una referencia numérica y el análisis de los errores obtenidos. En este caso, la referencia utilizada corresponde al método binomial americano.
"""

model.eval()

S_eval = torch.tensor(S_grid.reshape(-1,1), dtype=torch.float32).to(device)
t_eval = torch.zeros_like(S_eval).to(device)

with torch.no_grad():
    V_pinn_grid = model(S_eval, t_eval).cpu().numpy().flatten()

abs_error = np.abs(V_pinn_grid - V_binomial_grid)
rel_error = abs_error / (np.abs(V_binomial_grid) + 1e-8)

mask = V_binomial_grid > 1.0

mre = np.mean(rel_error[mask])
mae = np.mean(abs_error)

S0_tensor = torch.tensor([[S0]], dtype=torch.float32).to(device)
t0_tensor = torch.tensor([[0.0]], dtype=torch.float32).to(device)

with torch.no_grad():
    pinn_price = float(model(S0_tensor, t0_tensor).cpu().numpy()[0,0])

print("Precio estimado por PINN:", pinn_price)
print("Precio por árbol binomial:", binomial_price)
print("Error absoluto en S0:", abs(pinn_price - binomial_price))
print("MAE en la malla:", mae)
print("Error relativo medio filtrado:", mre)
print("Error relativo medio filtrado (%):", 100*mre)

error_table = pd.DataFrame({
    "S": S_grid,
    "Binomial": V_binomial_grid,
    "PINN": V_pinn_grid,
    "Error absoluto": abs_error,
    "Error relativo": rel_error
})

error_table.head(10)

"""El precio estimado por la PINN fue de 14.5033, mientras que el método binomial obtuvo 12.0832.

El error absoluto medio en la malla fue de 1.1824 y el error relativo medio filtrado fue de 8.12%. El error relativo se calculó únicamente donde el precio binomial es mayor a 1 dólar para evitar distorsiones cuando el valor de referencia es prácticamente cero.

## Sección 10. Gráficas de comparación de precios: PINN vs binomial

<br>

Siguiendo el enfoque del artículo, se presentan comparaciones gráficas entre las predicciones de la PINN y la referencia numérica, así como métricas visuales que permiten analizar la precisión y el comportamiento de la solución obtenida.
"""

plt.figure(figsize=(8,5))
plt.plot(S_grid, V_binomial_grid, label="Binomial americano")
plt.plot(S_grid, V_pinn_grid, "--", label="PINN")
plt.xlabel("Precio del activo S")
plt.ylabel("Precio de la put americana")
plt.title("Comparación PINN vs binomial")
plt.grid(True)
plt.legend()
plt.show()

"""La primera gráfica compara el precio de la opción estimado por la PINN contra el precio obtenido mediante el método binomial. Las curvas se mantienen muy cercanas en la mayor parte del dominio, lo que indica que la PINN logró aproximar adecuadamente la función de precio.

## **Error absoluto**
"""

plt.figure(figsize=(8,5))
plt.plot(S_grid, abs_error)
plt.xlabel("Precio del activo S")
plt.ylabel("Error absoluto")
plt.title("Error absoluto entre PINN y binomial")
plt.grid(True)
plt.show()

"""La gráfica muestra la diferencia absoluta entre el precio estimado por la PINN y el obtenido mediante el método binomial para distintos valores del activo subyacente.

Se observa que el error no es uniforme a lo largo del dominio. Esto es normal, ya que la sensibilidad del precio de la opción cambia dependiendo de la región analizada. Existen zonas donde ambas aproximaciones prácticamente coinciden y el error disminuye hasta valores cercanos a cero, mientras que en otras regiones las curvas se separan ligeramente y el error aumenta.

Aun así, el error absoluto permanece acotado en todo el dominio, con un valor máximo cercano a 2.6 dólares. Considerando que el precio de la opción en esa región se encuentra alrededor de 20 dólares, la diferencia entre ambos métodos sigue siendo relativamente pequeña. Esto indica que la PINN logra reproducir de forma adecuada la solución de referencia proporcionada por el método binomial.

## **Error relativo**
"""

# Gráfica de error relativo entre PINN y binomial

mask_rel = V_binomial_grid > 5.0

plt.figure(figsize=(8,5))
plt.plot(
    S_grid[mask_rel],
    100 * rel_error[mask_rel],
    linewidth=2
)

plt.xlabel("Precio del activo S")
plt.ylabel("Error relativo (%)")
plt.title("Error relativo entre PINN y binomial")
plt.grid(True)
plt.show()

"""La gráfica muestra el error relativo porcentual entre la solución obtenida por la PINN y la referencia binomial para distintos valores del activo subyacente.

Para evitar distorsiones numéricas cuando el precio de la opción es muy pequeño, se consideran los puntos donde el valor binomial es mayor a 5 dólares. En estas regiones el error relativo resulta más representativo de la calidad de la aproximación.

Se observa que el error relativo permanece bajo en la mayor parte del dominio y aumenta gradualmente conforme la opción pierde valor. En conjunto, los resultados indican que la PINN reproduce de forma adecuada la solución binomial en la región más relevante para la valuación de la opción put americana.

## Sección 11. Frontera óptima de ejercicio

La frontera óptima de ejercicio $B(t)$ separa la región donde conviene ejercer anticipadamente la put americana de la región donde conviene mantener la opción.

<br>

Al igual que en el artículo de referencia, se analiza la frontera óptima de ejercicio que separa las regiones de ejercicio y continuación de la opción americana. En este trabajo la frontera se obtiene a partir del método binomial y se utiliza tanto para el análisis financiero como para apoyar el entrenamiento de la PINN.
"""

# Frontera estimada por el método binomial
boundary_times = binomial_boundary[:, 0]
boundary_values = binomial_boundary[:, 1]

# Quitar NaN para poder comparar correctamente
mask_boundary = ~np.isnan(boundary_values)

boundary_times_clean = boundary_times[mask_boundary]
boundary_values_clean = boundary_values[mask_boundary]

"""### **Comparación PINN vs Binomial**"""

# Gráfica frontera PINN vs binomial

t_plot = torch.tensor(
    boundary_times_clean.reshape(-1,1),
    dtype=torch.float32
).to(device)

with torch.no_grad():
    boundary_pinn = boundary_model(t_plot).cpu().numpy().flatten()

plt.figure(figsize=(8,5))
plt.plot(boundary_times_clean, boundary_values_clean, label="Frontera binomial")
plt.plot(boundary_times_clean, boundary_pinn, "--", label="Frontera PINN")
plt.xlabel("Tiempo t")
plt.ylabel("Precio crítico S* - B(t)")
plt.title("Frontera óptima: PINN vs binomial | Exercise Boundary B(t) vs t")
plt.grid(True)
plt.legend()
plt.show()

boundary_mae = np.mean(np.abs(boundary_pinn - boundary_values_clean))
print("MAE frontera PINN vs binomial:", boundary_mae)

"""En la comparación PINN vs binomial, la frontera estimada por la PINN sigue de forma cercana la frontera obtenida por el método binomial. El MAE de frontera fue de 1.1876, lo cual indica una buena aproximación.

Se observa que la frontera binomial presenta pequeños "picos o escalones". Esto ocurre porque el árbol binomial trabaja sobre una discretización finita del tiempo y del precio del activo, por lo que la frontera óptima solo puede actualizarse en los nodos disponibles del árbol. Como consecuencia, la frontera aparece con una forma escalonada y con pequeñas oscilaciones locales.

Por otro lado, la frontera obtenida por la PINN es una función continua aprendida por una red neuronal, por lo que presenta una trayectoria más suave. En general, ambas curvas siguen la misma tendencia general y permanecen muy cercanas.

### **Trayectoria real de SPY y frontera óptima**
"""

# Comparación entre trayectoria real de SPY y fronteras de ejercicio

# Tiempo real asociado a los 60 precios históricos
t_real = np.linspace(0, T, len(data))
S_real = data["Close"].values.flatten()

# Frontera binomial interpolada en los mismos tiempos que SPY real
B_binomial_real = np.interp(
    t_real,
    boundary_times_clean,
    boundary_values_clean
)

# Frontera PINN evaluada en los mismos tiempos que SPY real
t_real_tensor = torch.tensor(
    t_real.reshape(-1, 1),
    dtype=torch.float32
).to(device)

with torch.no_grad():
    B_pinn_real = boundary_model(t_real_tensor).cpu().numpy().flatten()

plt.figure(figsize=(8,5))
plt.plot(t_real, S_real, label="SPY real")
plt.plot(t_real, B_binomial_real, label="B_binomial(t)")
plt.plot(t_real, B_pinn_real, "--", label="B_PINN(t)")

plt.xlabel("Tiempo t")
plt.ylabel("Precio")
plt.title("SPY real vs Exercise Boundary predicha")
plt.grid(True)
plt.legend()
plt.show()

"""En la gráfica con SPY real, se observa que la trayectoria del activo permanece por encima de ambas fronteras de ejercicio durante el periodo analizado. Esto sugiere que, bajo estos parámetros, no habría sido óptimo ejercer anticipadamente la opción durante la trayectoria observada.

### **Precio predicho de la opción sobre la trayectoria real de SPY**
"""

# Precio de la opción sobre la trayectoria real de SPY: PINN vs binomial

t_real = np.linspace(0, T, len(data))
S_real = data["Close"].values.flatten()

# Precio PINN evaluado sobre la trayectoria real
S_real_tensor = torch.tensor(S_real.reshape(-1,1), dtype=torch.float32).to(device)
t_real_tensor = torch.tensor(t_real.reshape(-1,1), dtype=torch.float32).to(device)

with torch.no_grad():
    V_pinn_real_path = model(S_real_tensor, t_real_tensor).cpu().numpy().flatten()

# Precio binomial evaluado sobre la trayectoria real
V_binomial_real_path = np.array([
    american_put_binomial(float(S), K, r, sigma, max(T - t, 1e-6), N=150)[0]
    for S, t in zip(S_real, t_real)
])

plt.figure(figsize=(8,5))
plt.plot(t_real, V_binomial_real_path, label="Binomial")
plt.plot(t_real, V_pinn_real_path, "--", label="PINN")

plt.xlabel("Tiempo t")
plt.ylabel("Precio de la opción")
plt.title("Precio de la opción sobre la trayectoria real de SPY")
plt.grid(True)
plt.legend()
plt.show()

"""Esta gráfica muestra el precio de la opción put americana a lo largo del tiempo, evaluando tanto la PINN como el método binomial sobre los precios reales observados de SPY.

A diferencia de la gráfica de frontera, aquí no se grafica directamente el precio del activo, sino el precio estimado de la opción para cada punto de la trayectoria real del subyacente. La comparación permite observar si la PINN reproduce de manera consistente el comportamiento del método binomial conforme evoluciona el precio de SPY en el tiempo.

### **Precio de la opción sobre la trayectoria real de SPY**
"""

# Precio de la opción sobre la trayectoria real de SPY
# PINN vs Binomial + Precio real del activo

t_real = np.linspace(0, T, len(data))
S_real = data["Close"].values.flatten()

# Precio PINN sobre la trayectoria real
S_real_tensor = torch.tensor(
    S_real.reshape(-1,1),
    dtype=torch.float32
).to(device)

t_real_tensor = torch.tensor(
    t_real.reshape(-1,1),
    dtype=torch.float32
).to(device)

with torch.no_grad():
    V_pinn_real_path = model(
        S_real_tensor,
        t_real_tensor
    ).cpu().numpy().flatten()

# Precio binomial sobre la trayectoria real
V_binomial_real_path = np.array([
    american_put_binomial(
        float(S),
        K,
        r,
        sigma,
        max(T - t, 1e-6),
        N=150
    )[0]
    for S, t in zip(S_real, t_real)
])

# ---------------------------
# Gráfica
# ---------------------------

fig, ax1 = plt.subplots(figsize=(9,5))

# Eje izquierdo: precio de la opción
ax1.plot(
    t_real,
    V_binomial_real_path,
    label="Put binomial",
    linewidth=2
)

ax1.plot(
    t_real,
    V_pinn_real_path,
    "--",
    label="Put PINN",
    linewidth=2
)

ax1.set_xlabel("Tiempo t")
ax1.set_ylabel("Precio de la opción")
ax1.grid(True)

# Eje derecho: precio real de SPY
ax2 = ax1.twinx()

ax2.plot(
    t_real,
    S_real,
    color="green",
    alpha=0.7,
    label="SPY real"
)

ax2.set_ylabel("Precio de SPY")

# Leyenda conjunta
lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()

ax1.legend(
    lines1 + lines2,
    labels1 + labels2,
    loc="best"
)

plt.title("Precio de la opción y trayectoria real de SPY")
plt.show()

"""La gráfica compara el precio de la opción put americana estimado mediante el método binomial y la PINN, evaluados sobre la trayectoria real observada de SPY.

**Se observa una relación inversa entre el precio del activo y el valor de la opción:**
*  Cuando SPY presenta caídas o periodos de menor precio, el valor de la opción aumenta, ya que el derecho de vender a un precio fijo se vuelve más valioso.
* Cuando SPY aumenta de valor, el precio de la put disminuye.

En general, la PINN reproduce adecuadamente la tendencia capturada por el método binomial, manteniendo un comportamiento consistente sobre datos reales del mercado.

Esta comparación permite validar que la PINN no solo aproxima la solución de referencia, sino que también responde de manera coherente a la evolución real del activo subyacente.

### **Tabla de valores de la frontera**
"""

boundary_df = pd.DataFrame({
    "t": boundary_times,
    "Frontera óptima S*": boundary_values
})

boundary_df.dropna().head(10)

"""La tabla muestra algunos valores discretos de la frontera óptima estimada por el método binomial. Estos valores complementan la gráfica al presentar numéricamente el precio crítico $B(t)$ para distintos tiempos.

## Sección 12. Interpretación financiera
"""

print("Interpretación financiera:")
print(f"Para SPY con S0 = {S0:.2f}, K = {K:.2f}, T = {T} años, r = {r} y sigma = {sigma:.4f}:")
print(f"La PINN estima un precio de {pinn_price:.4f}.")
print(f"El árbol binomial estima un precio de {binomial_price:.4f}.")
print(f"El MAE contra el método binomial fue de {mae:.4f}.")
print("Error relativo medio calculado solo donde el precio binomial es mayor a 1:", mre)
print("La frontera óptima indica los niveles de precio donde el inversionista debería considerar ejercer anticipadamente la opción put.")

"""Financieramente, una opción put americana aumenta de valor cuando disminuye el precio del activo subyacente, ya que otorga el derecho de vender a un precio fijo $K$. A diferencia de una opción europea, puede ejercerse antes del vencimiento, por lo que resulta importante estimar la frontera óptima de ejercicio $B(t)$.

Los resultados muestran que la PINN logró aproximar razonablemente el precio de la opción y la frontera de ejercicio. La comparación contra el método binomial permite validar numéricamente el desempeño del modelo. Además, al comparar la trayectoria real de SPY contra las fronteras estimadas, se observa que el activo permaneció por encima de la región de ejercicio anticipado durante el periodo analizado.
"""