# -*- coding: utf-8 -*-
"""Proyecto_Integrador_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PTuEptRS4LA_WUw9HRgJItFfr6OHfi5N
"""

pip install simpleai

# Definimos la clase Nave
import random
import simpleai.search as ss
from simpleai.search import SearchProblem, hill_climbing, simulated_annealing

class Nave:
    def __init__(self, nombre, posicion, gasolina):
        self.nombre = nombre
        self.posicion = posicion
        self.gasolina = gasolina

    def actualizar_posicion(self, nueva_posicion):
        self.posicion = nueva_posicion

    def gastar_gas(self, cantidad):
        self.gasolina -= cantidad

    def mandar_coordenadas(self):
        return self.posicion

    def mover(self, direccion, ambiente):
        x, y = self.posicion

        movimientos = {
            "arriba": (-1, 0),
            "abajo": (1, 0),
            "izquierda": (0, -1),
            "derecha": (0, 1),
            "diagonal_arriba_i": (-1, -1),
            "diagonal_arriba_d": (-1, 1),
            "diagonal_abajo_i": (1, -1),
            "diagonal_abajo_d": (1, 1),
        }

        if direccion in movimientos:
            dx, dy = movimientos[direccion]
            nuevo_x = x + dx
            nuevo_y = y + dy

            if not (0 <= nuevo_x < ambiente.filas and 0 <= nuevo_y < ambiente.columnas):
                print(f"La nave {self.nombre} no puede salir del mapa.")
                return

            valor_actual = ambiente.mapa_original[x][y]
            valor_nuevo = ambiente.mapa_original[nuevo_x][nuevo_y]

            if abs(valor_actual - valor_nuevo) > 1:
                print(f"La nave {self.nombre} no puede moverse porque el cambio en el nivel topográfico es mayor a 1. {valor_actual} → {valor_nuevo}")
                return

            if ambiente.mapa[nuevo_x][nuevo_y] == ' X':
                print(f"La nave {self.nombre} no puede moverse porque hay un obstáculo.")
                return

            if ambiente.mapa[nuevo_x][nuevo_y] == ' ~':
                print(f"¡La nave {self.nombre} ha encontrado agua!")
                return

            nivel_nuevo = ambiente.obtener_nivel((nuevo_x, nuevo_y))
            self.gastar_gas(nivel_nuevo)
            ambiente.actualizar_mapa(self, (nuevo_x, nuevo_y))


class Ambiente:
    def __init__(self, filas, columnas, cantidad_agua, cantidad_obstaculos, nave):
        self.filas = filas
        self.columnas = columnas
        self.nave = nave
        self.cantidad_agua = cantidad_agua
        self.cantidad_obstaculos = cantidad_obstaculos
        self.mapa = [[random.choice([0, 1, 2, 3, 4, 5]) for _ in range(columnas)] for _ in range(filas)]
        self.mapa_original = [fila[:] for fila in self.mapa]

        self.distribuir_elementos(cantidad_agua, ' ~')
        self.distribuir_elementos(cantidad_obstaculos, ' X')
        self.colocar_nave()

    def distribuir_elementos(self, cantidad, elemento):
        for _ in range(cantidad):
            while True:
                x = random.randint(0, self.filas - 1)
                y = random.randint(0, self.columnas - 1)
                if isinstance(self.mapa[x][y], int):
                    self.mapa[x][y] = elemento
                    break


    def colocar_nave(self):
        x, y = self.nave.posicion
        self.mapa[x][y] = '\033[1m N\033[0m'

    def actualizar_mapa(self, nave, nueva_posicion, nueva_gasolina):
        x_actual, y_actual = nave.posicion
        nueva_x, nueva_y = nueva_posicion

        # Restaura el valor original en la posición actual
        self.mapa[x_actual][y_actual] = self.mapa_original[x_actual][y_actual]

        # Mueve la nave a la nueva posición y actualiza la gasolina
        nave.actualizar_posicion(nueva_posicion)
        nave.gasolina = nueva_gasolina  # Actualiza el nivel de gasolina de la nave
        self.mapa[nueva_x][nueva_y] = '\033[1m N\033[0m'

    def mostrar_mapa(self):
        print(f'Mapa de {self.filas}x{self.columnas}:')
        print(f'Asigno nave {self.nave.nombre} como N')
        print(f"Nivel de gasolina {self.nave.gasolina} litros")
        print(f'Cantidad de agua {self.cantidad_agua}')
        print(f'Cantidad de obstáculos {self.cantidad_obstaculos}')
        print('_' * (self.columnas * 3 + 3))
        for fila in self.mapa:
            print('|' + " ".join(f'{value:2}' for value in fila) + '|')
        print('_' * (self.columnas * 3 + 3))

    def obtener_nivel(self, posicion):
        x, y = posicion
        if 0 <= x < self.filas and 0 <= y < self.columnas:
            return self.mapa_original[x][y]
        return None

class BusquedaAgua(SearchProblem):
    def __init__(self, nave, ambiente):
        self.nave = nave
        self.ambiente = ambiente
        super().__init__(initial_state=(nave.posicion, nave.gasolina))

    def actions(self, state):
        """ Devuelve las acciones válidas desde el estado actual """
        (x, y), gasolina = state
        movimientos = {
            "derecha": (0, 1),
            "abajo": (1, 0),
            "izquierda": (0, -1),
            "arriba": (-1, 0),
            "diagonal_abajo_derecha": (1, 1),
            "diagonal_abajo_izquierda": (1, -1),
            "diagonal_arriba_derecha": (-1, 1),
            "diagonal_arriba_izquierda": (-1, -1),
        }

        acciones_validas = []
        for accion, (dx, dy) in movimientos.items():
            nuevo_x, nuevo_y = x + dx, y + dy
            if 0 <= nuevo_x < self.ambiente.filas and 0 <= nuevo_y < self.ambiente.columnas:
                if self.ambiente.mapa_original[nuevo_x][nuevo_y] != 'X':  # No moverse a obstáculos
                    nivel_actual = self.ambiente.mapa_original[x][y]
                    nivel_nuevo = self.ambiente.mapa_original[nuevo_x][nuevo_y]
                    if abs(nivel_actual - nivel_nuevo) <= 1:  # Verificar cambio de nivel aceptable
                        costo_movimiento = nivel_nuevo + 1  # Calcular costo basado en el nivel
                        if gasolina >= costo_movimiento:
                            acciones_validas.append(accion)

        return acciones_validas

    def result(self, state, action):
        """ Retorna el nuevo estado después de realizar una acción """
        (x, y), gasolina = state
        movimientos = {
            "derecha": (0, 1),
            "abajo": (1, 0),
            "izquierda": (0, -1),
            "arriba": (-1, 0),
            "diagonal_abajo_derecha": (1, 1),
            "diagonal_abajo_izquierda": (1, -1),
            "diagonal_arriba_derecha": (-1, 1),
            "diagonal_arriba_izquierda": (-1, -1),
        }
        dx, dy = movimientos[action]
        nuevo_x, nuevo_y = x + dx, y + dy
        nivel_nuevo = self.ambiente.mapa_original[nuevo_x][nuevo_y]
        costo_movimiento = nivel_nuevo + 1
        nueva_gasolina = gasolina - costo_movimiento
        return ((nuevo_x, nuevo_y), nueva_gasolina)

    def is_goal(self, state):
        """ Define cuándo se ha encontrado agua """
        (x, y), _ = state
        return self.ambiente.mapa[x][y] == ' ~'  # Agua

    def heuristic(self, state):
        """ Heurística para A* (distancia Manhattan al agua más cercana) """
        (x, y), _ = state
        posiciones_agua = [(i, j) for i in range(self.ambiente.filas) for j in range(self.ambiente.columnas) if self.ambiente.mapa[i][j] == ' ~']
        if not posiciones_agua:
            return float("inf")  # Si no hay agua, heurística infinita
        return min(abs(x - ax) + abs(y - ay) for ax, ay in posiciones_agua)

# Creación de la nave y el ambiente
x = random.randint(0, 14)
y = random.randint(0, 29)

mi_nave = Nave('Robertito', (x, y), 100)
mi_ambiente = Ambiente(15, 30, 20, 10, mi_nave)
mi_ambiente.mostrar_mapa()

# Crear el problema de búsqueda
problema = BusquedaAgua(mi_nave, mi_ambiente)


class BusquedaMin(SearchProblem):
    def __init__(self, ambiente, posicion_inicial):
        self.ambiente = ambiente
        self.posicion_inicial = posicion_inicial
        self.initial_state = (posicion_inicial, 100, [posicion_inicial])
        super().__init__(initial_state=self.initial_state)

    def actions(self, state):
        (x, y), gasolina, movimientos = state
        acciones = []
        posibles_movimientos = [
            (-1, 0), (1, 0), (0, -1), (0, 1),  # Movimientos verticales y horizontales
            (-1, -1), (-1, 1), (1, -1), (1, 1)  # Movimientos diagonales
        ]

        for dx, dy in posibles_movimientos:
            nuevo_x, nuevo_y = x + dx, y + dy
            if 0 <= nuevo_x < self.ambiente.filas and 0 <= nuevo_y < self.ambiente.columnas:
                nivel_actual = self.ambiente.obtener_nivel((x, y))
                nuevo_nivel = self.ambiente.obtener_nivel((nuevo_x, nuevo_y))
                if isinstance(nuevo_nivel, int) and abs(nivel_actual - nuevo_nivel) == 1 and nuevo_nivel != ' X' and nuevo_nivel != ' ~':
                    costo_movimiento = nuevo_nivel + 1
                    nueva_gasolina = max(0, gasolina - costo_movimiento)
                    if nueva_gasolina > 0:
                        acciones.append((dx, dy))

        return acciones if acciones else []

    def result(self, state, action):
        (x, y), gasolina, movimientos = state
        dx, dy = action
        nuevo_x, nuevo_y = x + dx, y + dy
        nuevo_nivel = self.ambiente.obtener_nivel((nuevo_x, nuevo_y))
        costo_movimiento = nuevo_nivel + 1
        nueva_gasolina = max(0, gasolina - costo_movimiento)
        nuevo_movimientos = movimientos + [(nuevo_x, nuevo_y)]
        return ((nuevo_x, nuevo_y), nueva_gasolina, nuevo_movimientos)

    def value(self, state):
        (x, y), _, _ = state
        return -self.ambiente.mapa_original[x][y]

    def temperature(self, time):
        return max(0.1, 100 - time)  # Annealing Schedule

# Creación del ambiente y nave
x = random.randint(0, 14)
y = random.randint(0, 29)
inicial_posicion = (x, y)  # Guardar la posición inicial en una variable independiente
mi_nave = Nave('Robertito', inicial_posicion, 100)
mi_ambiente = Ambiente(15, 30, 20, 10, mi_nave)
mi_ambiente.mostrar_mapa()


def buscar_minimo(problem, search_method, metodo_nombre):
    print(f"\n--- {metodo_nombre} ---")
    iteraciones = 0
    max_iteraciones = 500  # Límite para evitar bucles infinitos

    while iteraciones < max_iteraciones:
        solution = search_method(problem)
        if mi_ambiente.obtener_nivel(solution.state[0]) == 0:
            break
        problem = BusquedaMin(mi_ambiente, inicial_posicion)
        iteraciones += 1

    print(f"Movimientos en {metodo_nombre}:")
    for step in solution.state[2]:
        print(step)
    print(f"{metodo_nombre} encontró la posición más profunda en: {solution.state[0]}")
    mi_ambiente.actualizar_mapa(mi_nave, solution.state[0], solution.state[1])
    mi_ambiente.mostrar_mapa()

# Ejecutar búsquedas
buscar_minimo(BusquedaMin(mi_ambiente, inicial_posicion), hill_climbing, "Hill Climbing")
buscar_minimo(BusquedaMin(mi_ambiente, inicial_posicion), hill_climbing, "Random-Restart Hill Climbing")
buscar_minimo(BusquedaMin(mi_ambiente, inicial_posicion), simulated_annealing, "Simulated Annealing")

# Encontrar máximo
class BusquedaMAx(BusquedaMin):
    def value(self, state):
        (x, y), _, _ = state
        return self.ambiente.mapa_original[x][y]


x = random.randint(0, 14)
y = random.randint(0, 29)
inicial_posicion = (x, y)
mi_nave = Nave('Robertito', inicial_posicion, 100)
mi_ambiente = Ambiente(15, 30, 20, 10, mi_nave)
mi_ambiente.mostrar_mapa()

def buscar_maximo(problem, search_method, metodo_nombre):
    print(f"\n--- {metodo_nombre} ---")
    iteraciones = 0
    max_iteraciones = 500

    while iteraciones < max_iteraciones:
        solution = search_method(problem)
        if mi_ambiente.obtener_nivel(solution.state[0]) == 5:
            break
        problem = BusquedaMAx(mi_ambiente, inicial_posicion)
        iteraciones += 1

    print(f"Movimientos en {metodo_nombre}:")
    for step in solution.state[2]:
        print(step)
    print(f"{metodo_nombre} encontró la posición más alta en: {solution.state[0]}")
    mi_ambiente.actualizar_mapa(mi_nave, solution.state[0], solution.state[1])
    mi_ambiente.mostrar_mapa()

buscar_maximo(BusquedaMAx(mi_ambiente, inicial_posicion), hill_climbing, "Hill Climbing")
buscar_maximo(BusquedaMAx(mi_ambiente, inicial_posicion), hill_climbing, "Random-Restart Hill Climbing")
buscar_maximo(BusquedaMAx(mi_ambiente, inicial_posicion), simulated_annealing, "Simulated Annealing")

# Algoritmo de calendarización
def schedule(t):
    T0 = 100  # Temperatura inicial alta
    alpha = 0.95  # Factor de enfriamiento ajustado
    return max(0.01, T0 * (alpha ** t))

# Prueba independiente de la calendarización
print("Prueba de la función de calendarización:")
for t in range(0, 21, 5):  # Imprime valores de temperatura en diferentes tiempos
    print(f"Tiempo {t}: Temperatura {schedule(t):.4f}")


buscar_maximo(HighestPointSearch(mi_ambiente, inicial_posicion),
              lambda p: simulated_annealing(p, schedule_logarithmic),
              "Simulated Annealing con Calendarización")