# -*- coding: utf-8 -*-
"""Clasificacion_Emociones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EEGyEHCDAP1PRQzfx0k_9JVjzdCXaAeg

<font face = "times new roman">
<center>
<img src = "https://javier.rodriguez.org.mx/itesm/2014/tecnologico-de-monterrey-blue.png" width = "250">
<h3></h3>
<h3>Diseño de Redes Neuronales y Aprendizaje Profundo</h3>
<h4>TC2035.301</h4>
<h4>Situación Problema</h4>
<h4>Zareth Abigail Rodríguez Reyes - A01659378</h4>
<h4>Karol Alexis Alvarado - A01751711</h4>
<h4>Profesora Andrea Torres</h4>

</center>
</font>

# Descripción del problema

El problema consiste en clasificar imágenes de rostros humanos en dos emociones: Happy y Sad, utilizando una red neuronal convolucional.

Se escogió la base de datos de Kaggle "Human_Face_Emotions". Contiene 2000 imágenes distribuidas equitativamente.

Este problema es de clasificación binaria.

Aplicaciones: visión por computadora como análisis emocional y sistemas inteligentes.

# Librerias
"""

# Importar librerías
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import random
from PIL import Image
import cv2
import glob
from tqdm.auto import tqdm
import os
import zipfile
plt.style.use('ggplot')

import os
import shutil

import seaborn as sns
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.utils.data import DataLoader, Dataset
import torch.nn.functional as F

from torchvision import datasets
from torchvision import transforms

# Establecer semillas aleatorias para la reproducibilidad
seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

"""# Importar conjunto de datos
Se escogió la base de datos de Kaggle "Human_Face_Emotions". Dado que el dataset original contenía más de 16k datos, se seleccionaron únicamente dos clases con 1000 imágenes cada uno. En total contiene 2000 imágenes distribuidas equitativamente.

Se sube como una carpeta zip.
"""

from google.colab import files
uploaded = files.upload()

local_zip = 'data.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content/data')
zip_ref.close()

data_path = Path("/content/data/data/data/")
image_path = data_path/"train"

for dirpath, dirnames, filenames in os.walk(image_path):
    print(f"Hay {len(filenames)} imágenes en '{dirpath}'.")

"""# Augmentation

"""

train_transforms = transforms.Compose([
    transforms.Resize((48, 48)), # Redimensionar a 48x48
    transforms.Grayscale(num_output_channels=1), # Convertir a escala de grises
    transforms.RandomHorizontalFlip(p=0.5), #Rotación de orientación
    transforms.RandomRotation(10), # Rotación aleatoria añadida
    transforms.ToTensor(), #Conversión a tensor
    transforms.Normalize(mean=[0.449], std=[0.226]) # Normalizar para escala de grises
])

test_transforms = transforms.Compose([
    transforms.Resize((48, 48)), # Redimensionar a 48x48
    transforms.Grayscale(num_output_channels=1), # Convertir a escala de grises
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.449], std=[0.226]) # Normalizar para escala de grises
])

full_dataset = datasets.ImageFolder(root=image_path)
print(f"{len(full_dataset)} imagenes.")

"""# Arquitectura

### Justificación de la arquitectura CNN

La arquitectura implementada está compuesta por tres bloques convolucionales seguidos de un clasificador completamente conectado. Cada bloque incluye:
- Convoluciones 3x3  
- Batch Normalization  
- Función de activación ReLU  
- MaxPooling  

**Tamaño de filtros (3x3):**  
Los filtros 3x3 son un estándar en CNN modernas porque permiten capturar bordes y texturas locales manteniendo bajo el número de parámetros. Esto mejora la eficiencia y facilita el entrenamiento.

**Aumento progresivo del número de canales (16 → 32 → 64 → 128):**  
Este incremento permite que la red aprenda una jerarquía de características:  
- Primer bloque: patrones simples como bordes.  
- Segundo bloque: estructuras intermedias del rostro.  
- Tercer bloque: patrones de alto nivel asociados a expresiones emocionales.  

**Número de capas:**  
Se eligieron tres bloques porque las imágenes del dataset (48x48) son pequeñas y no requieren redes profundas. Tres etapas son suficientes para extraer características relevantes sin caer en overfitting.

**Funciones de activación ReLU:**  
ReLU acelera la convergencia, evita el desvanecimiento del gradiente y funciona muy bien en arquitecturas profundas.

**Regularización utilizada:**  
- **Batch Normalization:** estabiliza las activaciones y permite entrenar más rápido y de manera más estable.  
- **Dropout (0.5):** reduce significativamente el overfitting en las capas densas apagando neuronas aleatoriamente.  
- **Data Augmentation:** rotaciones y flips aleatorios aumentan la variabilidad del dataset, mejorando la capacidad de generalización.  
- **Early Stopping:** previene overfitting deteniendo el proceso cuando el modelo deja de mejorar en validación.

Estas decisiones equilibran capacidad de representación, estabilidad durante el entrenamiento y control del overfitting.
"""

class CNNModel(nn.Module):
    def __init__(self, num_classes=2):
        super(CNNModel, self).__init__()
        # Primer bloque convolucional
        self.features = nn.Sequential(
            # Bloque 1
            # Patrones simples
            nn.Conv2d(1, 16, kernel_size=3, padding=1), # Los canales de entrada cambiaron a 1 para escala de grises
            nn.BatchNorm2d(16),
            nn.ReLU(),
            nn.Conv2d(16, 16, kernel_size=3, padding=1),
            nn.BatchNorm2d(16),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),    # Tamaño de salida: 16x24x24 (desde 16x48x48)
            # Esto hace la red más eficiente y mejora la recepción de nuevos datos

            # Bloque 2
            # Patrones intermedios
            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=3, padding=1), # Filtros aumentados a 64
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),    # Tamaño de salida: 64x12x12 (desde 64x24x24)

            # Bloque 3
            # Patrones completos: ojos, cejas, boca
            nn.Conv2d(64, 128, kernel_size=3, padding=1), # Filtros aumentados a 128
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.Conv2d(128, 128, kernel_size=3, padding=1), # Mantener filtros en 128
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)     # Tamaño de salida: 128x6x6 (desde 128x12x12)
        )

        # Clasificador (Capas densas)
        # Entrada a la capa lineal después de 3 capas MaxPool2d (48x48 -> 24x24 -> 12x12 -> 6x6)
        # Canales finales: 128
        self.classifier = nn.Sequential(
            nn.Dropout(0.5), #Evita el sobreajuste apagando aleatoriamente neuronas.
            nn.Linear(128 * 6 * 6, 1024), # Primera capa densa
            nn.ReLU(),
            nn.Dropout(0.5), # Segundo dropout
            nn.Linear(1024, 512), # Segunda capa densa
            nn.ReLU(),
            nn.Dropout(0.5), # Tercero dropout
            nn.Linear(512, num_classes) # Capa de salida con 2 clases
        )

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)  # Aplanar la salida para las capas completamente conectadas
        x = self.classifier(x)
        return x

# Instanciar el modelo
model = CNNModel(num_classes=len(full_dataset.classes))
print(model)

"""# Entorno de ejecución"""

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

model.to(device) # Mover a GPU

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

print(f"Device set to: {device}")
print("Loss function (criterion) initialized as CrossEntropyLoss.")
print("Optimizer initialized as Adam with learning rate 0.001.")

"""# Data split

Esta clase envuelve un subconjunto de datos (Subset) y aplica transformaciones (transforms) únicamente cuando se accede a cada imagen.

Torchvision.ImageFolder permite definir UN solo transform para todo el dataset. Sin embargo, nosotros necesitamos:
* transformaciones con data augmentation para train
* transformaciones  para test

Separar las transformaciones de esta manera evita aplicar augmentations al conjunto de prueba.
"""

import torch
from torch.utils.data import Dataset, Subset

class TransformedSubset(Dataset):
    def __init__(self, subset, transform=None):
        # subset: subconjunto creado con random_split()
        # transform: transformaciones específicas para este subconjunto
        self.subset = subset
        self.transform = transform

    def __getitem__(self, index):
        # Recuperamos la imagen y etiqueta del subset original
        x, y = self.subset[index]
        if self.transform:
            x = self.transform(x)

        # Regresamos imagen transformada + etiqueta
        return x, y

    def __len__(self):
        return len(self.subset)

total_size = len(full_dataset)
train_size = int(0.8 * total_size)
test_size = total_size - train_size

# Dividir el conjunto de datos en subconjuntos de entrenamiento y prueba crudos
train_subset_raw, test_subset_raw = torch.utils.data.random_split(full_dataset, [train_size, test_size])

# Aplicar transformaciones usando la clase TransformedSubset
train_dataset = TransformedSubset(train_subset_raw, transform=train_transforms)
test_dataset = TransformedSubset(test_subset_raw, transform=test_transforms)

print(f"Dataset split: train_size={len(train_dataset)}, test_size={len(test_dataset)}")

batch_size = 32
num_workers = 0 # Se cambió num_workers a 0 para evitar problemas de multiprocesamiento en Colab

train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers)
test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers)

print(f"Train DataLoader created with {len(train_dataloader)} batches of size {batch_size}.")
print(f"Test DataLoader created with {len(test_dataloader)} batches of size {batch_size}.")

"""# Modelo

## Entrenamiento del modelo

En esta sección se realiza el proceso completo de entrenamiento del modelo.  
El entrenamiento se ejecuta durante un máximo de **50 épocas**, registrando en cada una:

- **Loss de entrenamiento (train loss)**
- **Accuracy de entrenamiento**
- **Loss de validación (test loss)**
- **Accuracy de validación**

Esto permite analizar el progreso del aprendizaje y monitorear si el modelo está generalizando bien.

### Función de pérdida
Se utiliza `CrossEntropyLoss`, que es la función estándar para tareas de **clasificación multiclase**.  
Esta función compara los *logits* del modelo contra las etiquetas verdaderas y calcula el error que se utilizará para ajustar los pesos.

### Optimización mediante Backpropagation
En cada batch de entrenamiento se ejecutan los pasos clásicos:
1. **Forward pass**: el modelo genera una predicción.
2. **Cálculo del loss**.
3. **Backward pass**: se calculan gradientes.
4. **Actualización de pesos** mediante el optimizador Adam.

### Validación por época
Después de entrenar cada época, el modelo se evalúa sobre el conjunto de prueba:
- No se calculan gradientes (`torch.no_grad()`).
- No se aplican augmentations (solo `test_transforms`).
- Se calcula accuracy y loss de validación para medir generalización.

Esto permite comparar el desempeño entre *train* y *test* y detectar señales de overfitting.

### Early Stopping
Se implementa un mecanismo de **early stopping** para evitar overfitting.  
Este mecanismo detiene el entrenamiento si:

- El **test loss** no mejora durante `patience = 5` épocas consecutivas.
- La mejora mínima requerida es `min_delta = 0.001`.

Cada vez que el modelo mejora su desempeño en validación, se guardan sus **mejores pesos** (`best_model_state`).  
Al finalizar, se recargan dichos pesos para asegurar que el modelo final utilizado sea el mejor observado durante todo el entrenamiento.
"""

num_epochs = 50
train_losses = []
train_accuracies = []
test_losses = []
test_accuracies = []

# Cambiar la función de pérdida a CrossEntropyLoss
criterion = nn.CrossEntropyLoss()

model.to(device) # Asegurar que el modelo esté en el dispositivo correcto antes de comenzar el entrenamiento

# Parámetros de Early Stopping
best_test_loss = float('inf')
patience = 5
patience_counter = 0
min_delta = 0.001 # Cambio mínimo en la pérdida de prueba para ser considerado una mejora
best_model_state = None # Para almacenar los mejores pesos del modelo

for epoch in range(num_epochs):
    model.train() # Establecer el modelo en modo de entrenamiento
    total_train_loss = 0.0
    correct_predictions_train = 0
    total_samples_train = 0

    # Training loop
    for batch_idx, (inputs, labels) in enumerate(tqdm(train_dataloader, desc=f"Epoch {epoch+1} Training")):
        inputs, labels = inputs.to(device), labels.to(device)

        # Forward pass
        outputs = model(inputs)

        loss = criterion(outputs, labels)

        # Backpropagation and optimization
        optimizer.zero_grad() # Borrar gradientes anteriores
        loss.backward()       # Calcular gradientes
        optimizer.step()      # Actualizar parámetros del modelo

        total_train_loss += loss.item() * inputs.size(0)

        # Para clasificación multiclase, obtener predicciones encontrando el logit máximo
        _, predicted = torch.max(outputs.data, 1)

        # Asegurarse de que las etiquetas sean 'long' para la comparación con lo predicho
        correct_predictions_train += (predicted == labels).sum().item()
        total_samples_train += labels.size(0) # Usar labels.size(0) ya que es batch_size

    avg_train_loss = total_train_loss / total_samples_train
    train_accuracy = correct_predictions_train / total_samples_train
    train_losses.append(avg_train_loss)
    train_accuracies.append(train_accuracy)

    # Evaluation phase
    model.eval() # Establecer el modelo en modo de evaluación
    total_test_loss = 0.0
    correct_predictions_test = 0
    total_samples_test = 0

    with torch.no_grad(): # Deshabilitar el cálculo de gradientes para la evaluación
        for inputs, labels in tqdm(test_dataloader, desc=f"Epoch {epoch+1} Testing"):
            inputs, labels = inputs.to(device), labels.to(device)

            outputs = model(inputs)
            loss = criterion(outputs, labels)

            total_test_loss += loss.item() * inputs.size(0)

            _, predicted = torch.max(outputs.data, 1)
            correct_predictions_test += (predicted == labels).sum().item()
            total_samples_test += labels.size(0)

    avg_test_loss = total_test_loss / total_samples_test
    test_accuracy = correct_predictions_test / total_samples_test
    test_losses.append(avg_test_loss)
    test_accuracies.append(test_accuracy)

    print(f"Epoch [{epoch+1}/{num_epochs}], Train Loss: {avg_train_loss:.4f}, Train Accuracy: {train_accuracy:.4f}, Test Loss: {avg_test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}")

    # Early stopping
    if avg_test_loss < best_test_loss - min_delta:
        best_test_loss = avg_test_loss
        patience_counter = 0
        best_model_state = model.state_dict() # Guardar los mejores pesos del modelo
    else:
        patience_counter += 1
        if patience_counter >= patience:
            print(f"Early stopping triggered after {epoch+1} epochs due to no improvement in test loss for {patience} consecutive epochs.")
            break

# Cargar los mejores pesos del modelo si se produjo una detención temprana
if best_model_state is not None:
    model.load_state_dict(best_model_state)
    print("Loaded best model weights due to early stopping.")

print("Training complete.")

"""# Gráficas y métricas de evaluación

En esta sección analizamos el desempeño del modelo usando las curvas de entrenamiento, la matriz de confusión y las métricas finales obtenidas en el conjunto de prueba.

---

### Gráfica de Loss (Train vs Test)

- El **training loss** disminuye de manera estable durante las épocas.
- El **test loss** sigue una tendencia similar, con pequeñas oscilaciones normales.
- La cercanía entre ambas curvas indica que **no hay sobreajuste significativo**.
- El modelo logra aprender patrones relevantes sin perder capacidad de generalización.

---

### Gráfica de Accuracy (Train vs Test)

- La accuracy de entrenamiento alcanza aproximadamente **0.91**.
- La accuracy de prueba se mantiene entre **0.82–0.85**, confirmando un buen desempeño general.
- La diferencia entre ambas curvas es moderada, lo cual refleja que el modelo generaliza bien.

---
"""

import matplotlib.pyplot as plt

# Graficando pérdidas de entrenamiento y prueba
plt.figure(figsize=(10, 5))
plt.plot(range(1, len(train_losses) + 1), train_losses, label='Training Loss', color='blue')
plt.plot(range(1, len(test_losses) + 1), test_losses, label='Test Loss', color='red', linestyle='--')
plt.title('Training y Test Loss por Época')
plt.xlabel('Época')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

# Graficando precisiones de entrenamiento y prueba
plt.figure(figsize=(10, 5))
plt.plot(range(1, len(train_accuracies) + 1), train_accuracies, label='Training Accuracy', color='blue')
plt.plot(range(1, len(test_accuracies) + 1), test_accuracies, label='Test Accuracy', color='red', linestyle='--')
plt.title('Training y Test Accuracy por Epoch')
plt.xlabel('Época')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

model.eval() # Establecer el modelo en modo de evaluación

all_preds = []
all_labels = []

with torch.no_grad():
    for inputs, labels in tqdm(test_dataloader, desc="Evaluating on Test Set"):
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)

        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Convertir listas a arreglos numpy
all_preds = np.array(all_preds)
all_labels = np.array(all_labels)

print("Evaluación en el conjunto de prueba completada. Predicciones y etiquetas recolectadas.")

cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=full_dataset.classes,
            yticklabels=full_dataset.classes)
plt.xlabel('Predicción')
plt.ylabel('Verdadero')
plt.title('Matriz de confusión')
plt.show()

"""
### Matriz de Confusión

La matriz de confusión muestra cómo se comporta el modelo en cada clase:

- **Happy:** 178 predicciones correctas, 29 incorrectas.
- **Sad:** 152 predicciones correctas, 41 incorrectas.

Esto indica que el modelo funciona bien en ambas clases, aunque tiende ligeramente a confundir **Sad → Happy** más que el caso contrario."""

report = classification_report(all_labels, all_preds, target_names=full_dataset.classes)
print(report)

"""### Métricas Finales (Test Set)

| Clase | Precision | Recall | F1-score | Soporte |
|-------|-----------|--------|----------|---------|
| Happy | 0.81 | 0.86 | 0.84 | 207 |
| Sad   | 0.84 | 0.79 | 0.81 | 193 |

**Resultados globales:**
- **Accuracy total:** 0.82  
- **F1-score macro:** 0.82  
- Desempeño balanceado entre clases.

---

# Evaluación final

Previo a la evaluación final, se cargaron los mejores pesos obtenidos durante el entrenamiento (Early Stopping).
"""

# Seleccionar las imágenes de prueba al mismo tiempo
uploaded = files.upload()

import torch.nn.functional as F

def predict_image(model, img_tensor, device="cpu"):
    model = model.to(device)
    model.eval()

    # img_tensor debe tener forma (C, H, W)
    img_tensor = img_tensor.unsqueeze(0).to(device)  # -> (1, C, H, W)

    with torch.no_grad():
        output = model(img_tensor) # La salida del modelo son logits

        # Aplicar softmax para obtener probabilidades para cada clase
        probabilities = F.softmax(output, dim=1)

        # Obtener el índice de la clase predicha (0 o 1) encontrando el logit máximo
        _, predicted_class_idx = torch.max(output, 1)

    return probabilities, predicted_class_idx

def show_prediction(img_pil):
    plt.imshow(img_pil)
    plt.axis('off')
    plt.show()

for filename, filedata in uploaded.items():
    print(f"\nProcesando imagen: {filename}")
    # Abrir imagen
    img_pil = Image.open(filename).convert("RGB")
    show_prediction(img_pil)
    # Transformación para datos de prueba sin Aumento de Datos
    img_tensor = test_transforms(img_pil) # cambiado a test_transforms
    # Predecir
    y_probabilities, y_class_index_tensor = predict_image(model, img_tensor, device="cpu") # cnn cambiado a model
    print("Probabilidades: ", y_probabilities)
    # Nombres de clase
    class_names = full_dataset.classes
    predicted_class_index = int(y_class_index_tensor.item())
    predicted_class_name = class_names[predicted_class_index]
    print(f"Predicción: {predicted_class_name}")

"""### Conclusión breve
El modelo logra distinguir entre expresiones **Happy** y **Sad** con un desempeño sólido (82% de accuracy).  
Las curvas de aprendizaje son estables, la matriz de confusión muestra un buen nivel de acierto y las métricas por clase son consistentes, lo que confirma que la arquitectura y las técnicas de regularización utilizadas fueron efectivas.

---

## Dificultades y Lecciones Aprendidas

### Dificultad: variaciones en iluminación y ángulos
Las imágenes presentaban condiciones de iluminación, posiciones del rostro y ángulos muy distintos, lo cual generaba confusión en el modelo y dificultaba la extracción de patrones consistentes.  
**Solución:** El uso de *data augmentation* fue clave para mejorar la robustez del modelo ante estas variaciones.

---

### Lección: la normalización y el preprocesamiento son esenciales
Durante el desarrollo se observó que la normalización y las transformaciones adecuadas influyen tanto como la arquitectura.  
**Aprendizaje:** Un pipeline de preprocesamiento bien diseñado permite que el modelo aprenda de forma más estable y rápida.

---

### Lección: early stopping evita entrenamientos innecesarios
El entrenamiento prolongado sin mejora llevaba al riesgo de sobreajuste y aumento del error en validación.  
**Aprendizaje:** *Early stopping* ayudó a detener el entrenamiento en el momento óptimo, reduciendo overfitting y ahorrando tiempo computacional.
"""